import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'vi' | 'en';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  vi: {
    appName: 'Mate & Match',
    discover: 'Khám phá',
    chat: 'Trò chuyện',
    sos: 'SOS',
    settings: 'Cài đặt',
    login: 'Đăng nhập',
    email: 'Email',
    schoolEmail: 'Email Trường',
    password: 'Mật khẩu',
    confirmPassword: 'Xác nhận mật khẩu',
    forgotPassword: 'Quên mật khẩu?',
    dontHaveAccount: 'Chưa có tài khoản?',
    alreadyHaveAccount: 'Đã có tài khoản?',
    signUp: 'Đăng ký',
    createAccount: 'Tạo Tài Khoản',
    welcome: 'Chào mừng trở lại!',
    findYourTeam: 'Tìm đồng đội hoàn hảo cho dự án của bạn',
    thecarrier: 'Người Gánh Team 🎯',
    studybuddy: 'Bạn Học 📚',
    teambuilder: 'Người Xây Team 🤝',
    huntingA: 'Săn Điểm A+',
    justPass: 'Chỉ Cần Qua Môn',
    nightOwl: 'Cú Đêm',
    earlyBird: 'Chim Sớm',
    verified: 'Đã Xác Minh',
    trustScore: 'Điểm Uy Tín',
    badges: 'Huy Hiệu & Thành Tựu',
    skillStats: 'Chỉ Số Kỹ Năng',
    about: 'Giới Thiệu',
    inviteToTeam: 'Mời Vào Team',
    profileDetails: 'Chi Tiết Hồ Sơ',
    sosMode: 'Chế Độ SOS',
    findHelpFast: 'Tìm Trợ Giúp Nhanh',
    createSOSRequest: 'Tạo Yêu Cầu SOS',
    whatDoYouNeed: 'Bạn cần gì?',
    deadline: 'Hạn Chót',
    offer: 'Đề Nghị (Tùy chọn)',
    sendSOSRequest: 'Gửi Yêu Cầu SOS',
    availableNow: 'Sẵn Sàng Ngay',
    request: 'Yêu Cầu',
    rateTeammate: 'Đánh Giá Đồng Đội',
    projectCompleted: 'Dự án hoàn thành',
    punctuality: 'Đúng Giờ (Có bỏ rơi không?)',
    qualityOfWork: 'Chất Lượng Công Việc',
    communication: 'Giao Tiếp',
    anonymousFeedback: 'Phản Hồi Ẩn Danh (Tùy chọn)',
    submitReview: 'Gửi Đánh Giá',
    feedbackHelps: 'Phản hồi của bạn giúp xây dựng cộng đồng đáng tin cậy',
    messages: 'Tin Nhắn',
    noMessages: 'Chưa có tin nhắn nào',
    startMatching: 'Bắt đầu khớp để trò chuyện!',
    reviews: 'Đánh Giá',
    account: 'Tài Khoản',
    notifications: 'Thông Báo',
    privacy: 'Quyền Riêng Tư',
    language: 'Ngôn Ngữ',
    logout: 'Đăng Xuất',
    yourReviews: 'Đánh Giá Của Bạn',
    noReviews: 'Chưa có đánh giá nào',
    completeProjects: 'Hoàn thành dự án để nhận đánh giá!',
    leadership: 'Lãnh Đạo',
    slideDesign: 'Thiết Kế Slide',
    slidedesign: 'Thiết Kế Slide',
    research: 'Nghiên Cứu',
    presentation: 'Thuyết Trình',
    contentWriting: 'Viết Nội Dung',
    contentwriting: 'Viết Nội Dung',
    timeManagement: 'Quản Lý Thời Gian',
    timemanagement: 'Quản Lý Thời Gian',
    joinCommunity: 'Tham gia cộng đồng sinh viên đáng tin cậy',
    studentInfo: 'Thông Tin Sinh Viên',
    fullName: 'Họ và Tên',
    studentId: 'Mã Số Sinh Viên',
    university: 'Trường Đại Học',
    major: 'Ngành Học',
    selectUniversity: 'Chọn trường đại học',
    selectMajor: 'Chọn ngành học',
    continue: 'Tiếp Tục',
    accountSecurity: 'Bảo Mật Tài Khoản',
    useSchoolEmail: 'Sử dụng email trường để xác minh',
    passwordMismatch: 'Mật khẩu không khớp',
    back: 'Quay Lại',
    editProfile: 'Chỉnh Sửa Hồ Sơ',
    help: 'Trợ Giúp',
    termsOfService: 'Điều Khoản Dịch Vụ',
    filters: 'Bộ Lọc',
    distance: 'Khoảng Cách',
    goal: 'Mục Tiêu',
    workStyle: 'Phong Cách Làm Việc',
    archetype: 'Vai Trò',
    reset: 'Đặt Lại',
    applyFilters: 'Áp Dụng Bộ Lọc',
    allArchetypes: 'Tất Cả Vai Trò',
    enableFilters: 'Bật Bộ Lọc',
    disableFilters: 'Tắt Bộ Lọc',
    filtersEnabled: 'Bộ lọc đang bật',
    filtersDisabled: 'Bộ lọc đang tắt - Hiển thị tất cả',
    viewMyProfile: 'Xem Hồ Sơ Của Tôi',
    online: 'Trực Tuyến',
    offline: 'Ngoại Tuyến',
    typeMessage: 'Nhập tin nhắn...',
    searchMessages: 'Tìm kiếm tin nhắn...',
    profileVisibility: 'Hiển Thị Hồ Sơ',
    showProfileToOthers: 'Cho phép người khác xem hồ sơ của bạn',
    showEmailAddress: 'Hiển Thị Địa Chỉ Email',
    displayEmailOnProfile: 'Hiển thị email trên hồ sơ của bạn',
    showUniversity: 'Hiển Thị Trường',
    displayUniversityInfo: 'Hiển thị thông tin trường đại học',
    allowMessages: 'Cho Phép Tin Nhắn',
    letOthersSendMessages: 'Cho phép người khác gửi tin nhắn cho bạn',
    showOnlineStatus: 'Hiển Thị Trạng Thái Trực Tuyến',
    letOthersSeeOnline: 'Cho phép người khác biết khi bạn trực tuyến',
    saveChanges: 'Lưu Thay Đổi',
    newMatches: 'Khớp Mới',
    notifyNewMatches: 'Nhận thông báo khi có người khớp với bạn',
    receiveMessageNotifications: 'Nhận thông báo tin nhắn',
    sosRequests: 'Yêu Cầu SOS',
    urgentHelpRequests: 'Yêu cầu trợ giúp khẩn cấp từ đồng đội',
    projectInvites: 'Lời Mời Dự Án',
    whenInvitedToTeam: 'Khi bạn được mời tham gia đội',
    reviewNotifications: 'Thông Báo Đánh Giá',
    whenTeammatesReview: 'Khi đồng đội đánh giá bạn',
    writeNewReview: 'Viết Đánh Giá Mới',
    viewAll: 'Xem Tất Cả',
    requested: 'Đã Yêu Cầu',
    emailCannotBeChanged: 'Email không thể thay đổi',
    tapToChangePhoto: 'Nhấn để thay đổi ảnh',
    enterImageUrl: 'Nhập URL hình ảnh cho demo:',
    enterYourUniversity: 'Nhập Trường Của Bạn',
    typeUniversityName: 'Nhập tên trường đại học của bạn',
    enterYourMajor: 'Nhập Ngành Của Bạn',
    typeMajorName: 'Nhập tên ngành học của bạn',
    allCaughtUp: 'Bạn Đã Xem Hết!',
    checkedEveryone: 'Bạn đã xem tất cả mọi người trong khu vực. Quay lại sau hoặc điều chỉnh bộ lọc!',
    reviewAgain: 'Xem Lại',
    adjustFilters: 'Điều Chỉnh Bộ Lọc',
    rememberMe: 'Ghi Nhớ Đăng Nhập',
    streakCalendar: 'Lịch Chuỗi Ngày',
    dayStreak: 'Ngày Liên Tiếp',
    keepStreakGoing: 'Tiếp tục đăng nhập mỗi ngày để duy trì chuỗi ngày của bạn!',
    letsGo: 'Bắt Đầu Thôi!',
    current: 'Hiện Tại',
    longest: 'Dài Nhất',
    totalDays: 'Tổng Số Ngày',
    milestones: 'Mốc Quan Trọng',
    days: 'Ngày',
    firstWeekStreak: '🎉 Tuần Đầu Tiên!',
    monthStreak: '🔥 Một Tháng Liên Tiếp!',
    fiftyDayStreak: '⭐ 50 Ngày Tuyệt Vời!',
    hundredDayStreak: '🏆 100 Ngày Xuất Sắc!',
    amazingStreak: '🌟 Chuỗi Ngày Tuyệt Vời!',
    badgeCollection: 'Bộ Sưu Tập Huy Hiệu',
    badgesUnlocked: 'Huy Hiệu Đã Mở',
    unlockedBadges: 'Huy Hiệu Đã Mở Khóa',
    lockedBadges: 'Huy Hiệu Bị Khóa',
    unlocked: 'Đã Mở',
    // Project Board
    projects: 'Dự Án',
    projectBoard: 'Bảng Dự Án',
    findSpecificProjects: 'Tìm dự án cụ thể để tham gia',
    platformStats: 'Thống Kê Nền Tảng',
    hide: 'Ẩn',
    activeStudents: 'Sinh Viên Hoạt Động',
    projectCompletion: 'Hoàn Thành Dự Án',
    successfulMatches: 'Khớp Thành Công',
    thisWeek: 'Tuần Này',
    allProjects: 'Tất Cả Dự Án',
    noProjectsYet: 'Chưa Có Dự Án Nào',
    beFirstToPost: 'Hãy là người đầu tiên tạo dự án!',
    createProject: 'Tạo Dự Án',
    viewDetails: 'Xem Chi Tiết',
    members: 'Thành Viên',
    applicants: 'Ứng Viên',
    verifiedProject: 'Dự Án Đã Xác Minh',
    verifiedByProfessor: 'Đã được giảng viên xác nhận',
    projectDescription: 'Mô Tả Dự Án',
    skillsNeeded: 'Kỹ Năng Cần Thiết',
    teamSize: 'Quy Mô Nhóm',
    preferredWorkStyle: 'Phong Cách Làm Việc Ưa Thích',
    flexible: 'Linh Hoạt',
    applyToProject: 'Ứng Tuyển Dự Án',
    shareAvailability: 'Chia Sẻ Lịch Trống',
    selectAvailableSlots: 'Chọn khung giờ bạn có thể làm việc',
    dynamicAvailability: 'Cập nhật linh hoạt theo thời gian thực',
    yourCommitment: 'Cam Kết Của Bạn',
    canMeetDeadlines: 'Tôi có thể đáp ứng deadline',
    availableForMeetings: 'Tôi sẵn sàng họp nhóm',
    willCommunicate: 'Tôi sẽ giao tiếp tích cực',
    cancel: 'Hủy',
    sendApplication: 'Gửi Ứng Tuyển',
    accountabilityReminder: 'Lưu Ý Trách Nhiệm',
    trackingMilestones: 'Chúng tôi theo dõi các mốc quan trọng để đảm bảo cam kết',
    applicationSent: 'Ứng tuyển đã được gửi!',
    projectTitle: 'Tiêu Đề Dự Án',
    description: 'Mô Tả',
    projectGoal: 'Mục Tiêu Dự Án',
    step: 'Bước',
    morningWork: 'Làm việc buổi sáng sớm',
    eveningWork: 'Làm việc buổi tối / đêm',
    adaptableSchedule: 'Lịch làm việc linh hoạt',
    projectPreview: 'Xem Trước Dự Án',
    untitled: 'Chưa Đặt Tên',
    noDescription: 'Chưa có mô tả',
    // Major translations
    'International Business': 'Kinh Doanh Quốc Tế',
    'Computer Science': 'Khoa Học Máy Tính',
    'Business Administration': 'Quản Trị Kinh Doanh',
    'Marketing': 'Marketing',
    'Finance & Banking': 'Tài Chính & Ngân Hàng',
    'Data Science': 'Khoa Học Dữ Liệu',
    'Economics': 'Kinh Tế Học',
    'International Relations': 'Quan Hệ Quốc Tế',
  },
  en: {
    appName: 'Mate & Match',
    discover: 'Discover',
    chat: 'Chat',
    sos: 'SOS',
    settings: 'Settings',
    login: 'Login',
    email: 'Email',
    schoolEmail: 'School Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    signUp: 'Sign Up',
    createAccount: 'Create Account',
    welcome: 'Welcome Back!',
    findYourTeam: 'Find your perfect teammates for group projects',
    thecarrier: 'The Carrier 🎯',
    studybuddy: 'Study Buddy 📚',
    teambuilder: 'Team Builder 🤝',
    huntingA: 'Hunting A+',
    justPass: 'Just Pass',
    nightOwl: 'Night Owl',
    earlyBird: 'Early Bird',
    verified: 'Verified',
    trustScore: 'Trust Score',
    badges: 'Badges & Achievements',
    skillStats: 'Skill Stats',
    about: 'About',
    inviteToTeam: 'Invite to Team',
    profileDetails: 'Profile Details',
    sosMode: 'SOS Mode',
    findHelpFast: 'Find help fast',
    createSOSRequest: 'Create SOS Request',
    whatDoYouNeed: 'What do you need?',
    deadline: 'Deadline',
    offer: 'Offer (Optional)',
    sendSOSRequest: 'Send SOS Request',
    availableNow: 'Available Now',
    request: 'Request',
    rateTeammate: 'Rate Teammate',
    projectCompleted: 'Project completed',
    punctuality: 'Punctuality (Did they ghost?)',
    qualityOfWork: 'Quality of Work',
    communication: 'Communication',
    anonymousFeedback: 'Anonymous Feedback (Optional)',
    submitReview: 'Submit Review',
    feedbackHelps: 'Your feedback helps build a trustworthy community',
    messages: 'Messages',
    noMessages: 'No messages yet',
    startMatching: 'Start matching to chat!',
    reviews: 'Reviews',
    account: 'Account',
    notifications: 'Notifications',
    privacy: 'Privacy',
    language: 'Language',
    logout: 'Logout',
    yourReviews: 'Your Reviews',
    noReviews: 'No reviews yet',
    completeProjects: 'Complete projects to get reviews!',
    leadership: 'Leadership',
    slideDesign: 'Slide Design',
    slidedesign: 'Slide Design',
    research: 'Research',
    presentation: 'Presentation',
    contentWriting: 'Content Writing',
    contentwriting: 'Content Writing',
    timeManagement: 'Time Management',
    timemanagement: 'Time Management',
    joinCommunity: 'Join the trusted student community',
    studentInfo: 'Student Information',
    fullName: 'Full Name',
    studentId: 'Student ID',
    university: 'University',
    major: 'Major',
    selectUniversity: 'Select your university',
    selectMajor: 'Select your major',
    continue: 'Continue',
    accountSecurity: 'Account Security',
    useSchoolEmail: 'Use school email for verification',
    passwordMismatch: 'Passwords do not match',
    back: 'Back',
    editProfile: 'Edit Profile',
    help: 'Help',
    termsOfService: 'Terms of Service',
    filters: 'Filters',
    distance: 'Distance',
    goal: 'Goal',
    workStyle: 'Work Style',
    archetype: 'Archetype',
    reset: 'Reset',
    applyFilters: 'Apply Filters',
    allArchetypes: 'All Archetypes',
    enableFilters: 'Enable Filters',
    disableFilters: 'Disable Filters',
    filtersEnabled: 'Filters enabled',
    filtersDisabled: 'Filters disabled - Showing all',
    viewMyProfile: 'View My Profile',
    online: 'Online',
    offline: 'Offline',
    typeMessage: 'Type a message...',
    searchMessages: 'Search messages...',
    profileVisibility: 'Profile Visibility',
    showProfileToOthers: 'Show your profile to others',
    displayEmailOnProfile: 'Display email on your profile',
    showEmailAddress: 'Show Email Address',
    showUniversity: 'Show University',
    displayUniversityInfo: 'Display university information',
    allowMessages: 'Allow Messages',
    letOthersSendMessages: 'Let others send you messages',
    showOnlineStatus: 'Show Online Status',
    letOthersSeeOnline: "Let others see when you're online",
    saveChanges: 'Save Changes',
    newMatches: 'New Matches',
    notifyNewMatches: 'Get notified when someone matches with you',
    receiveMessageNotifications: 'Receive message notifications',
    sosRequests: 'SOS Requests',
    urgentHelpRequests: 'Urgent help requests from teammates',
    projectInvites: 'Project Invites',
    whenInvitedToTeam: "When you're invited to join a team",
    reviewNotifications: 'Reviews',
    whenTeammatesReview: 'When teammates review you',
    writeNewReview: 'Write New Review',
    viewAll: 'View All',
    requested: 'Requested',
    emailCannotBeChanged: 'Email cannot be changed',
    tapToChangePhoto: 'Tap to change photo',
    enterImageUrl: 'Enter image URL for demo:',
    enterYourUniversity: 'Enter Your University',
    typeUniversityName: 'Type your university name',
    enterYourMajor: 'Enter Your Major',
    typeMajorName: 'Type your major',
    allCaughtUp: "You're All Caught Up!",
    checkedEveryone: "You've seen everyone in your area. Check back later for new teammates or adjust your filters!",
    reviewAgain: 'Review Again',
    adjustFilters: 'Adjust Filters',
    rememberMe: 'Remember Me',
    streakCalendar: 'Streak Calendar',
    dayStreak: 'Day Streak',
    keepStreakGoing: 'Keep logging in daily to maintain your streak!',
    letsGo: 'Let\'s Go!',
    current: 'Current',
    longest: 'Longest',
    totalDays: 'Total Days',
    milestones: 'Milestones',
    days: 'Days',
    firstWeekStreak: '🎉 First Week!',
    monthStreak: '🔥 One Month Streak!',
    fiftyDayStreak: '⭐ 50 Day Streak!',
    hundredDayStreak: '🏆 100 Day Streak!',
    amazingStreak: '🌟 Amazing Streak!',
    badgeCollection: 'Badge Collection',
    badgesUnlocked: 'Badges Unlocked',
    unlockedBadges: 'Unlocked Badges',
    lockedBadges: 'Locked Badges',
    unlocked: 'Unlocked',
    // Project Board
    projects: 'Projects',
    projectBoard: 'Project Board',
    findSpecificProjects: 'Find specific projects to join',
    platformStats: 'Platform Stats',
    hide: 'Hide',
    activeStudents: 'Active Students',
    projectCompletion: 'Project Completion',
    successfulMatches: 'Successful Matches',
    thisWeek: 'This Week',
    allProjects: 'All Projects',
    noProjectsYet: 'No Projects Yet',
    beFirstToPost: 'Be the first to post a project!',
    createProject: 'Create Project',
    viewDetails: 'View Details',
    members: 'Members',
    applicants: 'Applicants',
    verifiedProject: 'Verified Project',
    verifiedByProfessor: 'Verified by Professor',
    projectDescription: 'Project Description',
    skillsNeeded: 'Skills Needed',
    teamSize: 'Team Size',
    preferredWorkStyle: 'Preferred Work Style',
    flexible: 'Flexible',
    applyToProject: 'Apply to Project',
    shareAvailability: 'Share Availability',
    selectAvailableSlots: 'Select available slots',
    dynamicAvailability: 'Dynamic Availability',
    yourCommitment: 'Your Commitment',
    canMeetDeadlines: 'Can meet deadlines',
    availableForMeetings: 'Available for meetings',
    willCommunicate: 'Will communicate',
    cancel: 'Cancel',
    sendApplication: 'Send Application',
    accountabilityReminder: 'Accountability Reminder',
    trackingMilestones: 'Tracking Milestones',
    applicationSent: 'Application sent!',
    projectTitle: 'Project Title',
    description: 'Description',
    projectGoal: 'Project Goal',
    step: 'Step',
    morningWork: 'Morning Work',
    eveningWork: 'Evening Work',
    adaptableSchedule: 'Adaptable Schedule',
    projectPreview: 'Project Preview',
    untitled: 'Untitled',
    noDescription: 'No Description',
    // Major translations (same as English)
    'International Business': 'International Business',
    'Computer Science': 'Computer Science',
    'Business Administration': 'Business Administration',
    'Marketing': 'Marketing',
    'Finance & Banking': 'Finance & Banking',
    'Data Science': 'Data Science',
    'Economics': 'Economics',
    'International Relations': 'International Relations',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'vi' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
